<?php

namespace Database\Seeders;

use App\Models\EgateLog;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class EgateLogSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $logs = [
            [
                'student_number' => '2026-00001',
                'last_name' => 'Dela Cruz',
                'first_name' => 'Maria',
                'middle_name' => 'Santos',
                'sex' => 'Female',
                'department' => 'College of Computing Studies',
                'course' => 'BS Information Technology',
                'year_level' => '1st Year',
                'grade_level' => '1st Year',
                'status' => 'IN',
                'logged_at' => Carbon::now()->subMinutes(3),
                'gate_name' => 'Main Gate',
                'ip_address' => '192.168.1.21',
                'remarks' => 'RFID access granted',
            ],
            [
                'student_number' => '2026-00002',
                'last_name' => 'Reyes',
                'first_name' => 'John Paul',
                'middle_name' => 'Villanueva',
                'sex' => 'Male',
                'department' => 'College of Computing Studies',
                'course' => 'BS Computer Science',
                'year_level' => '2nd Year',
                'grade_level' => '2nd Year',
                'status' => 'OUT',
                'logged_at' => Carbon::now()->subMinutes(8),
                'gate_name' => 'North Gate',
                'ip_address' => '192.168.1.35',
                'remarks' => 'Exit logged successfully',
            ],
            [
                'student_number' => '2026-00003',
                'last_name' => 'Garcia',
                'first_name' => 'Angela',
                'middle_name' => 'Lopez',
                'sex' => 'Female',
                'department' => 'College of Engineering',
                'course' => 'BS Civil Engineering',
                'year_level' => '3rd Year',
                'grade_level' => '3rd Year',
                'status' => 'IN',
                'logged_at' => Carbon::now()->subMinutes(12),
                'gate_name' => 'Main Gate',
                'ip_address' => '192.168.1.48',
                'remarks' => 'Face match verified',
            ],
            [
                'student_number' => '2026-00004',
                'last_name' => 'Mendoza',
                'first_name' => 'Carlo',
                'middle_name' => 'Ramos',
                'sex' => 'Male',
                'department' => 'College of Business Administration',
                'course' => 'BS Accountancy',
                'year_level' => '4th Year',
                'grade_level' => '4th Year',
                'status' => 'IN',
                'logged_at' => Carbon::now()->subMinutes(18),
                'gate_name' => 'East Gate',
                'ip_address' => '192.168.1.52',
                'remarks' => 'Manual verification passed',
            ],
            [
                'student_number' => '2026-00005',
                'last_name' => 'Torres',
                'first_name' => 'Bea',
                'middle_name' => 'Fernandez',
                'sex' => 'Female',
                'department' => 'College of Education',
                'course' => 'BSEd English',
                'year_level' => '2nd Year',
                'grade_level' => '2nd Year',
                'status' => 'OUT',
                'logged_at' => Carbon::now()->subMinutes(27),
                'gate_name' => 'South Gate',
                'ip_address' => '192.168.1.66',
                'remarks' => 'Exit after afternoon class',
            ],
            [
                'student_number' => '2026-00006',
                'last_name' => 'Navarro',
                'first_name' => 'Ethan',
                'middle_name' => 'Diaz',
                'sex' => 'Male',
                'department' => 'College of Computing Studies',
                'course' => 'BS Information Systems',
                'year_level' => '1st Year',
                'grade_level' => '1st Year',
                'status' => 'IN',
                'logged_at' => Carbon::now()->subMinutes(34),
                'gate_name' => 'Main Gate',
                'ip_address' => '192.168.1.73',
                'remarks' => 'New enrollee orientation access',
            ],
            [
                'student_number' => '2026-00007',
                'last_name' => 'Aquino',
                'first_name' => 'Sofia',
                'middle_name' => 'Lim',
                'sex' => 'Female',
                'department' => 'College of Nursing',
                'course' => 'BS Nursing',
                'year_level' => '3rd Year',
                'grade_level' => '3rd Year',
                'status' => 'IN',
                'logged_at' => Carbon::now()->subMinutes(41),
                'gate_name' => 'West Gate',
                'ip_address' => '192.168.1.84',
                'remarks' => 'Laboratory duty check-in',
            ],
            [
                'student_number' => '2026-00008',
                'last_name' => 'Castro',
                'first_name' => 'Miguel',
                'middle_name' => 'Perez',
                'sex' => 'Male',
                'department' => 'College of Arts and Sciences',
                'course' => 'BA Communication',
                'year_level' => '4th Year',
                'grade_level' => '4th Year',
                'status' => 'OUT',
                'logged_at' => Carbon::now()->subMinutes(55),
                'gate_name' => 'North Gate',
                'ip_address' => '192.168.1.92',
                'remarks' => 'Media team field assignment',
            ],
            [
                'student_number' => '2026-00009',
                'last_name' => 'Luna',
                'first_name' => 'Patricia',
                'middle_name' => 'Ocampo',
                'sex' => 'Female',
                'department' => 'College of Engineering',
                'course' => 'BS Electrical Engineering',
                'year_level' => '2nd Year',
                'grade_level' => '2nd Year',
                'status' => 'IN',
                'logged_at' => Carbon::now()->subHour()->subMinutes(6),
                'gate_name' => 'East Gate',
                'ip_address' => '192.168.1.107',
                'remarks' => 'Project consultation access',
            ],
            [
                'student_number' => '2026-00010',
                'last_name' => 'Bautista',
                'first_name' => 'Noah',
                'middle_name' => 'Rivera',
                'sex' => 'Male',
                'department' => 'College of Hospitality Management',
                'course' => 'BS Hospitality Management',
                'year_level' => '1st Year',
                'grade_level' => '1st Year',
                'status' => 'IN',
                'logged_at' => Carbon::now()->subHour()->subMinutes(15),
                'gate_name' => 'South Gate',
                'ip_address' => '192.168.1.118',
                'remarks' => 'Morning practicum attendance',
            ],
            [
                'student_number' => '2026-00011',
                'last_name' => 'Santiago',
                'first_name' => 'Claire',
                'middle_name' => 'Manalo',
                'sex' => 'Female',
                'department' => 'College of Education',
                'course' => 'BEEd General Education',
                'year_level' => '4th Year',
                'grade_level' => '4th Year',
                'status' => 'OUT',
                'logged_at' => Carbon::now()->subHour()->subMinutes(24),
                'gate_name' => 'Main Gate',
                'ip_address' => '192.168.1.126',
                'remarks' => 'Practice teaching dismissal',
            ],
            [
                'student_number' => '2026-00012',
                'last_name' => 'Flores',
                'first_name' => 'Adrian',
                'middle_name' => 'Tan',
                'sex' => 'Male',
                'department' => 'College of Computing Studies',
                'course' => 'BS Computer Science',
                'year_level' => '3rd Year',
                'grade_level' => '3rd Year',
                'status' => 'IN',
                'logged_at' => Carbon::now()->subHour()->subMinutes(36),
                'gate_name' => 'West Gate',
                'ip_address' => '192.168.1.139',
                'remarks' => 'Capstone consultation access',
            ],
        ];

        foreach ($logs as $log) {
            EgateLog::updateOrCreate(
                [
                    'student_number' => $log['student_number'],
                    'logged_at' => $log['logged_at'],
                ],
                $log
            );
        }
    }
}
